merged with branches/lsc/libmboard_simplify_comms

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -10,11 +10,13 @@ DIST_SUBDIRS = $(SUBDIRS) tests
 INCLUDEDIR = $(top_srcdir)/include
 
 include_HEADERS = $(INCLUDEDIR)/mboard.h \
+                  $(INCLUDEDIR)/mb_config.h \
 			      $(INCLUDEDIR)/mb_objmap.h
 noinst_HEADERS  = $(INCLUDEDIR)/mb_common.h \
 			      $(INCLUDEDIR)/mb_serial.h \
 			      $(INCLUDEDIR)/mb_parallel.h \
 			      $(INCLUDEDIR)/mb_utils.h \
+			      $(INCLUDEDIR)/mb_memlog.h \
 			      $(INCLUDEDIR)/mb_syncqueue.h \
 			      $(INCLUDEDIR)/mb_commqueue.h \
 			      $(INCLUDEDIR)/mb_pooled_list.h \
@@ -36,11 +38,11 @@ libmboard_sd_la_LIBADD  = src/utils/lib_utils_d.la src/serial/lib_mb_sd.la
 if COMPILE_PARALLEL
 libmboard_p_la_SOURCES  =
 libmboard_p_la_LDFLAGS  = @MB_PARALLEL_LDFLAGS@
-libmboard_p_la_LIBADD   = src/utils/lib_utils.la src/parallel/lib_mb_p.la @MB_PARALLEL_LIBS@
+libmboard_p_la_LIBADD   = src/utils/lib_utils_p.la src/parallel/lib_mb_p.la @MB_PARALLEL_LIBS@
 
 libmboard_pd_la_SOURCES =
 libmboard_pd_la_LDFLAGS = @MB_PARALLEL_LDFLAGS@
-libmboard_pd_la_LIBADD  = src/utils/lib_utils_d.la src/parallel/lib_mb_pd.la @MB_PARALLEL_LIBS@
+libmboard_pd_la_LIBADD  = src/utils/lib_utils_pd.la src/parallel/lib_mb_pd.la @MB_PARALLEL_LIBS@
 endif
 
 EXTRA_DIST = \
@@ -90,6 +92,42 @@ doc: Doxyfile_user Doxyfile_developer_serial Doxyfile_developer_parallel
 	@echo "Generating Developer documentation (parallel code) in ./doc/developer/parallel"
 	@doxygen Doxyfile_developer_parallel
 
+	@touch Doxyfile_user
+	@touch Doxyfile_developer_serial
+	@touch Doxyfile_developer_parallel
+	
 vclean:
 	(cd tests; make clean)
 	make clean
+
+# Options for splint
+# -D__sigset_t=int hides problems with splint trying to parse headers
+# used by pthread.h
+SPLINT_OPTIONS = -weak -D__sigset_t=int
+
+splint:
+	@( \
+	SPLINT=`splint --help 2>/dev/null`; \
+	if test ! $$? = 0; then \
+		echo "** 'splint' command not found" >&2; \
+		echo "** It is available from http://www.splint.org/" >&2; \
+		echo -e "\n"; \
+		exit 1; \
+	fi; \
+	)
+	@echo -e "\n----- (Checking src/utils/*.c)"
+	@splint $(SPLINT_OPTIONS) -I$(INCLUDEDIR) src/utils/*.c 
+	@echo -e "\n----- (Checking src/serial/*.c)"
+	@splint $(SPLINT_OPTIONS) -I$(INCLUDEDIR) src/serial/*.c 
+if COMPILE_PARALLEL
+	@( \
+	iflags=""; \
+	for i in dummy @MB_PARALLEL_CFLAGS@; do f=`echo $${i} | grep '^-I'`; iflags="$${iflags} $${f}"; done; \
+	echo -e "\n----- (Checking src/parallel/*.c)"; \
+	splint $(SPLINT_OPTIONS) $${iflags} -I$(INCLUDEDIR) src/parallel/*.c; \
+	) 
+endif
+if TESTS_CONFIGURED
+	@echo -e "\n ----- (Entering test directory: ./tests) "
+	(cd tests && make splint)
+endif
diff --git a/tests/Makefile.am b/tests/Makefile.am
--- a/tests/Makefile.am
+++ b/tests/Makefile.am
@@ -15,6 +15,7 @@ SUBDIRS = testsuite_commqueue \
           testsuite_mb_parallel \
           testsuite_mb_serial \
           testsuite_objmap \
+          testsuite_tag_table \
           testsuite_pooled_list \
           testsuite_syncqueue
           
@@ -57,6 +58,7 @@ run_test_utils_LDFLAGS  = @CUNITLDFLAGS@
 run_test_utils_CFLAGS   = -I$(INCLUDEDIR) @CUNITCFLAGS@ @DEBUG_CFLAGS@
 run_test_utils_LDADD    = $(testcode_dir)/testsuite_objmap/lib_t_objmap.la \
                           $(testcode_dir)/testsuite_pooled_list/lib_t_pooled_list.la \
+                          $(testcode_dir)/testsuite_tag_table/lib_t_tag_table.la \
 						  $(top_srcdir)/src/utils/lib_utils.la \
 						  @CUNITLIBS@
 
@@ -83,11 +85,58 @@ if COMPILE_PARALLEL
 	@echo -e "\n\n"
 endif
 
+# Options for splint
+# -D__sigset_t=int hides problems with splint trying to parse headers
+# used by pthread.h
+SPLINT_OPTIONS = -weak -D__sigset_t=int -warnposix
+SERIAL_TESTSUITES = objmap tag_table pooled_list mb_serial
+PARALLEL_TESTSUITES = syncqueue commqueue commroutines mb_parallel 
+
+splint:
+	@( \
+	SPLINT=`splint --help 2>/dev/null`; \
+	if test ! $$? = 0; then \
+		echo "** 'splint' command not found" >&2; \
+		echo "** It is available from http://www.splint.org/" >&2; \
+		echo -e "\n"; \
+		exit 1; \
+	fi; \
+	)
+	@echo -e "\n----- (in ./tests: Checking ./*.c)"
+	@splint $(SPLINT_OPTIONS) -I$(INCLUDEDIR) -I/usr/local/include *.c 
+	@( \
+	iflags=""; \
+	for i in dummy @MB_PARALLEL_CFLAGS@ @CUNITCFLAGS@ ; do \
+		f=`echo $${i} | grep '^-I'`; \ 
+		iflags="$${iflags} $${f}"; \
+	done; \
+	for ts in $(SERIAL_TESTSUITES); do \
+		echo -e "\n----- (in ./tests: Checking ./testsuite_$${ts}/*.c)"; \
+		splint $(SPLINT_OPTIONS) $${iflags} -I$(INCLUDEDIR) -I/usr/local/include testsuite_$${ts}/*.c; \
+	done; \
+	) 
+if COMPILE_PARALLEL
+	@( \
+	iflags=""; \
+	for i in dummy @MB_PARALLEL_CFLAGS@ @CUNITCFLAGS@ ; do \
+	f=`echo $${i} | grep '^-I'`; \ 
+	iflags="$${iflags} $${f}"; \
+	done; \
+	for ts in $(PARALLEL_TESTSUITES); do \
+		echo -e "\n----- (in ./tests: Checking ./testsuite_$${ts}/*.c)"; \
+		splint $(SPLINT_OPTIONS) $${iflags} -I$(INCLUDEDIR) -I/usr/local/include testsuite_$${ts}/*.c; \
+	done; \
+	)  
+endif
+
 else
 
 all: run
+splint: run
 
 run:
 	@echo -e "\n\n** Building of tests was disabled during ./configure"
 	
 endif
+
+
