mboard-config.in: introduced faster+versatile option parsing ChangeLog: minor edit

diff --git a/src/progs/mboard-config.in b/src/progs/mboard-config.in
--- a/src/progs/mboard-config.in
+++ b/src/progs/mboard-config.in
@@ -384,7 +384,8 @@ function ignore_option {
     fi
 }
 
-
+# Check if long option is acceptable
+# Uses global var - $acceptable_long_options
 function is_acceptable_option {
 
     option="$1"
@@ -394,49 +395,41 @@ function is_acceptable_option {
         if [ "$option" == "$key" ]
         then
             echo true
+            return 0
         fi
     done
 
     echo false
 }
 
+# Check if long option is acceptable
+# Uses global var - $acceptable_short_options
 function is_acceptable_short_option {
 
     option="$1"
+    list=$acceptable_short_options
     
-    if [ "$acceptable_short_options" == "" ]
+    # RHS=(LHS with $option removed)
+    # hence, if RHS != LHS, $option exist in list
+    if [ "$list" != "${list/$option/}" ]
     then
-    	# Generate list
-    	for lkey in $acceptable_long_options
-    	do
-    		skey=`get_short_from_long $lkey`
-    		acceptable_short_options="$skey $acceptable_short_options"
-    	done
-    fi
-    
-    for skey in $acceptable_short_options
-    do
-        if [ "$option" == "$skey" ]
-        then
-            echo true
-        fi
-    done
-
-    echo false
-
+        echo true
+   	else
+        echo false
+	fi
 }
 
-# This list will be used by functions:
+# These lists will be used by functions:
 # * is_acceptable_option
 # * is_acceptable_short_option
 # * parse_long_options
 acceptable_long_options="usage help version parallel serial \
                          cflags ldflags debug query libs mpi"
+acceptable_short_options="uhvVplscdqLm"
 
-# This list will be generated by is_acceptable_short_option when needed
-acceptable_short_options="" # DO NOT DEFINE MANUALLY!
 
 # parse input arguments
+# Uses global vars - $acceptable_short_options and $acceptable_long_options
 # TODO: Add support for autocompletion (eg. --ver -> --version)
 function parse_input_arguments {
 
@@ -489,23 +482,32 @@ function parse_input_arguments {
                 rtfm $ERR_USAGE
             fi
             
-            # treat -xyz as -x -y -z
-            temp_arg=${arg:1} # remove first char ('-')
-            while [ "$temp_arg" != "" ]
-            do
-                # pop first char from $temp_arg
-                firstchar=${temp_arg:0:1}
-                temp_arg=${temp_arg:1}
-                
-                if `is_acceptable_short_option "$firstchar"`
-                then
-                    recurse="-$firstchar $recurse"
-                else
-                    echo "(mboard-config) ERROR: Unknown option : -$firstchar"
-                    rtfm $ERR_USAGE
-                fi
-            done
             
+            temp_arg=${arg:1} # remove first char ('-')
+            
+            if `is_acceptable_option "$temp_arg"`
+            then
+                echo "(mboard-config) NOTE: Assuming you meant '--$temp_arg' instead of '-$temp_arg'" >&2
+                recurse="--$temp_arg $recurse"
+                
+            else # treat -xyz as -x -y -z
+                  
+	            while [ "$temp_arg" != "" ]
+	            do
+	                # pop first char from $temp_arg
+	                firstchar=${temp_arg:0:1}
+	                temp_arg=${temp_arg:1}
+	                
+	                if `is_acceptable_short_option "$firstchar"`
+	                then
+	                    recurse="-$firstchar $recurse"
+	                else
+	                    echo "(mboard-config) ERROR: Unknown option : -$firstchar"
+	                    rtfm $ERR_USAGE
+	                fi
+	            done
+            
+            fi
         # if arg does not start with '-'
         else
 
